### ISSUE TITLE
I keep on getting this error 

### ISSUE THREAD

**Issue by gamerdj325** [LITdevs/SaladBind#110]
ECONNREFUSED 127.42.0.1:443 
I don't know what to do and am generally confused.
I allowed it in my anti-virus but it still comes up.

**Comment by TheBlueBurger** [comment]
Please come in the discord server for support, but it seems like your antivirus/firewall is blocking it

**Comment by Vukkyy** [comment]
@gamerdj325 Did you try to download a miner? If yes, please tell me which one - we may have messed up a miner download link.

**Comment by gamerdj325** [comment]
sorry for the long text yes it appeared in pheonix miner but I got it all fixed out
