### ISSUE TITLE
Miner priority

### ISSUE THREAD

**Issue by leamir** [LITdevs/SaladBind#117]
## Your suggestion
I suggest the addition of a way to set the process priority for the miner

## Why should this be implemented?
Sometimes you are doing something that is light for the gpu, but the miner keeps using all of the power, and you can't use the program you are trying. A way to fix is to lower the priority of the miner, or to raise the priority of the program you are using

**Comment by vtheskeleton** [comment]
I dont think we should implement #117.
The correct way to decrease the miners usage is to set the intensity with advanced commands, usually -i and a value between 1 and 25

**Comment by leamir** [comment]
problem with setting the intensity is that you need to restart the miner to change those values, and if you forget to set it back after closing the program you were using, it still mantains the lower hashrate. With priority you can open and close any programs and it will adapt to it automatically
