### ISSUE TITLE
Discord RPC Bug

### ISSUE THREAD

**Issue by dotpeak** [LITdevs/SaladBind#127]
## Description
Discord RPC showing some miners as [Object object] 
## How to reproduce
To reproduce this bug enable Discord RPC in settings, start mining with T-Rex using ethash with prohashing. If you view the Discord RPC sometimes it will show up like this [https://cdn.peak.ovh/ikVBQa.png] .

**Comment by vtheskeleton** [comment]
When you experience this bug, do you run the app with the `-l` argument or use latest miner?

**Comment by dotpeak** [comment]
> When you experience this bug, do you run the app with the `-l` argument or use latest miner?

Latest miner afaik.

**Comment by vtheskeleton** [comment]
And if you try running it normally, do you still experience the issue?

**Comment by dotpeak** [comment]
Latest miner is without touching the settings of the miner right? Because I never touched the settings other then doing anything thats required.

**Comment by vtheskeleton** [comment]
latest miner is selecting "use latest miner" instead of "start mining"

**Comment by Craftzman7** [comment]
Experiencing this as well. Using "start mining" causes the bug as well.

**Comment by vtheskeleton** [comment]
@memedmusic have fun

**Comment by memedmusic** [comment]
Hi @dotpeak, after doing some testing I have not been able to reproduce this bug. I would appreciate it if you could send me your last.json file so I can further investigate this issue. (last.json can be found in %localappdata%\SaladBind\Data on windows)

**Comment by Craftzman7** [comment]
No longer experiencing this. Its just working now... for some reason. Not sure about @dotpeak

**Comment by EaGamesInc** [comment]
Hi peak

**Comment by vtheskeleton** [comment]
looks like this doesnt happen anymore?
