### ISSUE TITLE
AndroidOS/Multiverse Trojan

### ISSUE THREAD

**Issue by LeDeliJelly** [LITdevs/SaladBind#137]
## Description
Windows Defender flags Phoenix Miner as a trojan? 
![image](https://user-images.githubusercontent.com/92609665/147524571-1b4e29c5-1e07-4bfc-9dc4-cac3322b33eb.png)

## How to reproduce
Open SaladBind for the first time and choose Phoenix Miner.

**Comment by TheBlueBurger** [comment]
This is a false positive to prevent cryptojacking (running a miner on another person's machine without permission), but since you wanted to mine on your machine you can whitelist it
