### ISSUE TITLE
XMRig does not work

### ISSUE THREAD

**Issue by Hamziee** [LITdevs/SaladBind#139]
## Description
When I try to mine with XMRig, it gives me an error: "Access denied" There is no anti-virus. And when I download XMRig manually it works.
## How to reproduce
Select the XMRig miner, and try to start mining.

**Comment by vtheskeleton** [comment]
This is an issue on your end, If youre on Windows, check windows defender

**Comment by Hamziee** [comment]
I had to reinstall XMRig, in the folder where it was located. Then it worked
