### ISSUE TITLE
u MF CANT U COMMENT THEN FIGHT STOP CLOSEING MY ISSUES LIKEE A PUSSY

### ISSUE THREAD

**Issue by EaGamesInc** [LITdevs/SaladBind#151]
STOP CLOSEING MY ISSUES LIKE A PUSSY AND FUCKING FIGHT BACK U IDIOT

**Comment by memedmusic** [comment]
@Vukkyy or @vtheskeleton please block this person from the repo when you get a chance. I don’t have the required permission

**Comment by EaGamesInc** [comment]
gyayyy doesnt have perms LOLOLOLOL
