### ISSUE TITLE
Can't start saladbind-linux 

### ISSUE THREAD

**Issue by tristanzwart** [LITdevs/SaladBind#180]
## Description

If I try to start it it will give an error and fail also tried the other commands and searched online (took me about 5 hours still does not work)

## How to reproduce

Install Linux Mint 19.3.
Download the latest release for Linux.
Execute the first command in a terminal.
Then the second one.
That will result in an error saying something like this:
Can't execute binary file wrong executable file can't execute.

**Comment by TheBlueBurger** [comment]
Solved on Discord, issue was a 32-bit OS.
