### ISSUE TITLE
spawn C:\FFmpeg\bin ENOENT

### ISSUE THREAD

**Issue by TheBlueBurger** [LITdevs/SaladBind#185]
## Description
The error comes when you start mining, after you press "Yes" in the final prompt.
## How to reproduce
Currently unknown
## Media

https://user-images.githubusercontent.com/58081413/150820049-3295e617-0d16-4522-a67e-21f3e535f5ae.mp4
[bugreport.txt](https://github.com/LITdevs/SaladBind/files/7926974/bugreport.txt)

**Comment by Vukkyy** [comment]
It's hard to reproduce a bug without knowing how to reproduce it. Please provide more details.

**Comment by TheBlueBurger** [comment]
> It's hard to reproduce a bug without knowing how to reproduce it. Please provide more details.

I really don't have more details, you can ask the person who had the issue
