### ISSUE TITLE
SaladBind Owner

### ISSUE THREAD

**Issue by CharasLover30** [LITdevs/SaladBind#209]
6512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527shitassprogram651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527651235276512352765123527

**Comment by Vukkyy** [comment]
Hello, I am still able to view your original revision.

> Please be kind to content creators/Youtuber i never knew that saladbind didnot wanted other to make guide i spent 3 hours on making one and then i got a strike he could have contacted me by discord or anything but no he did not when i talked he was a toxic guy i need to wait 58 days for it to expire GL with this shit program :crossed_fingers: 

You have contacted me multiple times about this. Due to your professional responses, I will not resolve your strike. Please wait for it to expire.

**Comment by vtheskeleton** [comment]
Take this as a lesson for how to deal with people in a professional setting, you don't go scream in their faces.
![image](https://user-images.githubusercontent.com/47392011/163194902-be51585c-37eb-434e-a942-4594a6bc7296.png)

Sincerely, this is not a issue with our open source project.
